// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmpWR9kamFn0bBbU2mGhLtNIIw34-vwZo',
    appId: '1:171778149253:web:d9048890dcc10dc6e3d2ec',
    messagingSenderId: '171778149253',
    projectId: 'nearbarbershop2',
    authDomain: 'nearbarbershop2.firebaseapp.com',
    storageBucket: 'nearbarbershop2.appspot.com',
    measurementId: 'G-YJBNRS3W7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwlZwivhBRAyKnrpn9obgk_qzqVZMTGFQ',
    appId: '1:171778149253:android:9e606e4b088229c6e3d2ec',
    messagingSenderId: '171778149253',
    projectId: 'nearbarbershop2',
    storageBucket: 'nearbarbershop2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA41cWiP9WlWlaPCRJ4p3Wm3VkMYkPIPgs',
    appId: '1:171778149253:ios:51f10f7bb854c93fe3d2ec',
    messagingSenderId: '171778149253',
    projectId: 'nearbarbershop2',
    storageBucket: 'nearbarbershop2.appspot.com',
    androidClientId: '171778149253-imttkvpd51fcjf4vd2ejkgf6rl65ql75.apps.googleusercontent.com',
    iosClientId: '171778149253-dfbteqaeeti0q32e7je87s24jc14r6v8.apps.googleusercontent.com',
    iosBundleId: 'com.example.nearbarbershop2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA41cWiP9WlWlaPCRJ4p3Wm3VkMYkPIPgs',
    appId: '1:171778149253:ios:51f10f7bb854c93fe3d2ec',
    messagingSenderId: '171778149253',
    projectId: 'nearbarbershop2',
    storageBucket: 'nearbarbershop2.appspot.com',
    androidClientId: '171778149253-imttkvpd51fcjf4vd2ejkgf6rl65ql75.apps.googleusercontent.com',
    iosClientId: '171778149253-dfbteqaeeti0q32e7je87s24jc14r6v8.apps.googleusercontent.com',
    iosBundleId: 'com.example.nearbarbershop2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmpWR9kamFn0bBbU2mGhLtNIIw34-vwZo',
    appId: '1:171778149253:web:7eb8fe96cfceb79de3d2ec',
    messagingSenderId: '171778149253',
    projectId: 'nearbarbershop2',
    authDomain: 'nearbarbershop2.firebaseapp.com',
    storageBucket: 'nearbarbershop2.appspot.com',
    measurementId: 'G-36342W7KJC',
  );
}
